name: Master Pipeline

on:
  workflow_dispatch:

jobs:
  build_tickers:
    uses: ./.github/workflows/build_tickers.yml

  calculate_rs:
    uses: ./.github/workflows/Calculate RS.yml
    needs: build_tickers

  split_rs:
    uses: ./.github/workflows/split-rs-stocks.yml
    needs: calculate_rs
